# Numpy

### Q1) Create an array of 28 elements (0-27) using arange and reshape it as 2D 

In [1]:
import numpy as np
n=np.arange(28).reshape(7,4)
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

### Q2) Create an array with 30 elements (0-30) , reshape it as (6,5), extract [[17,18,19],[22,23,24]], extract 29 from the matrix.

In [2]:
import numpy as np
e=np.arange(30).reshape(6,5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [6]:
e[3:5,2:]

array([[17, 18, 19],
       [22, 23, 24]])

In [7]:
e[5:,4:]

array([[29]])

In [8]:
e[5,4]

29

### Q3) Find the sum of the array, sum of rows and sum of columns

In [9]:
e.sum()

435

In [16]:
e.sum(axis=1) #axis=0 stands for columns, axis=1 stands for rows

array([ 10,  35,  60,  85, 110, 135])

In [17]:
e.sum(axis=0)

array([75, 81, 87, 93, 99])