In [3]:
import numpy as np

Q1)Convert the given Python list into NumPy array and check its data type

In [5]:
list_1=[5,3,7,1,6]

In [6]:
#Write the codings here
data = np.array(list_1)
data,type(data)

(array([5, 3, 7, 1, 6]), numpy.ndarray)

Q2)Generate array [0,1,2,3,4,5,6,7,8,9]  using NumPy built-in function, arange()

In [7]:
#Write the codings here
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q3) Generate arrays of 5 integer 1's

In [2]:
#Write the codings here
import numpy as np
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

Q4)Generate the following matrix

In [8]:
#Write the codings here
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Q5) Generate 5 zero's of float datatype 

In [11]:
#Write the codings here
np.zeros(5)

array([0., 0., 0., 0., 0.])

Q6)Use arange() to generate an array of even numbers between 40 and 100.(40 and 100 are not included)

In [ ]:
#Write the codings here

Q7)Generate an array of 10 linearly spaced points between 10 and 100.
Output step size as well?

In [ ]:
#Write the codings here

Q8)Perform the following tasks:

* Generate a vector array of 25 numbers using arange()
* write a code to convert the vector array into 2-D matrix using reshape
* can we use shape instead of reshape as well?

In [ ]:
#Write the codings here

Q9)Write a code to generate a 7x5 matrix of 35 random numbers?
Notice, there are no ( ) in the output matrix!

In [ ]:
#Write the codings here

Q10)Generate the following matrix using NumPy's built-in method for identity matrix.

In [12]:
#Write the codings here

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

Q11) Create an array of 28 elements (0-27) using arange and reshape it as 2D array

In [ ]:
#Write the codings here

Q12) Create an array with 30 elements (0-30) , reshape it as (6,5), extract [[17,18,19],[22,23,24]], extract 29 from the matrix.

In [ ]:
#Write the codings here

Q13) Write a code to generate a 7x5 matrix of 35 random numbers?

In [ ]:
#Write the codings here

Q14) calculate the sum of all the numbers in array_2d?

In [ ]:
#Write the codings here

Q15)Calculate sum of all the rows and columns in array_2d.

In [ ]:
#Write the codings here