In [1]:
import numpy as np

In [4]:
#array
a=np.array([10,25,45,6,7])
a

array([10, 25, 45,  6,  7])

In [11]:
#sequences array with particular range
a_range=np.arange(10,25)
a_range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
#2d array
d2=np.array([[2,4],[6,7]])
d2

array([[2, 4],
       [6, 7]])

In [12]:
#shaping with 2d array 
shape=np.arange(30).reshape(5,6)
shape

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [13]:
shape.shape

(5, 6)

In [14]:
shape.size

30

In [15]:
type(shape)

numpy.ndarray

In [17]:
# array with zeros
zero=np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np1=np.arange(15).reshape(5,3)
np1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [20]:
np2=np.arange(9).reshape(3,3)
np2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
# merging vertically when cols size has same in both numpy object
np.vstack((np1,np2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [22]:
np3=np.arange(9).reshape(3,3)
np4=np.arange(12).reshape(3,4)


In [23]:
np3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
np4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
# merging horizontlly when rows size has same in both numpy object

np.hstack((np3,np4))

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11]])

In [27]:
# Randome sequences

rm=np.random.random() # 0 to 1 
rm

0.10145749975199192

In [30]:
# ramdom with 2d array
rm=np.random.random((2,3)) 
rm

array([[0.08974378, 0.30561368, 0.9419735 ],
       [0.85810944, 0.96977439, 0.3429823 ]])

In [35]:
# rounding lowest and nerest int 
fl=np.floor(np.random.random((2,3)))
print(fl)
print('---')
fl2=np.floor(100*np.random.random((2,3)))
fl2

[[0. 0. 0.]
 [0. 0. 0.]]
---


array([[51., 43.,  1.],
       [64., 70., 84.]])

In [37]:
# rounding lowest and nerest int 

np.floor(10.4)

10.0

In [38]:
# rounding highest and nerest int 
np.ceil(10.4)

11.0

In [40]:
fl2=np.floor(100*np.random.random((2,6)))
fl2

array([[64., 74., 30., 65., 13., 97.],
       [23., 75.,  0.,  4., 72., 25.]])

In [42]:
#spliting array in horizontally

np.hsplit(fl2,3)

[array([[64., 74.],
        [23., 75.]]),
 array([[30., 65.],
        [ 0.,  4.]]),
 array([[13., 97.],
        [72., 25.]])]

In [43]:
fl3=np.floor(100*np.random.random((8,2)))
fl3

array([[14., 66.],
       [30., 54.],
       [73., 17.],
       [14., 99.],
       [31., 71.],
       [35., 84.],
       [28., 14.],
       [63., 17.]])

In [46]:
#spliting array in vertically

np.vsplit(fl3,4)

[array([[14., 66.],
        [30., 54.]]),
 array([[73., 17.],
        [14., 99.]]),
 array([[31., 71.],
        [35., 84.]]),
 array([[28., 14.],
        [63., 17.]])]

In [47]:
# references of numpy object

ori=np.array([1,3,4,5])
ori

array([1, 3, 4, 5])

In [48]:
ref=ori
ref

array([1, 3, 4, 5])

In [49]:
ori

array([1, 3, 4, 5])

In [50]:
ori[2]=10
ori

array([ 1,  3, 10,  5])

In [51]:
ref

array([ 1,  3, 10,  5])

In [53]:
ref1=ori.copy()
ref1

array([ 1,  3, 10,  5])

In [54]:
ori

array([ 1,  3, 10,  5])

In [55]:
ori[2]=12
ori

array([ 1,  3, 12,  5])

In [56]:
ref1

array([ 1,  3, 10,  5])