# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [12]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [10]:
np.random.random(1)

array([0.5788199])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [50]:
np.random.normal(0,1,25)

array([-1.26455479e-01, -2.52624526e-01,  3.65548816e-01, -1.15632437e+00,
        8.66827790e-02, -2.75632130e-01, -8.09917315e-01, -7.08709514e-01,
       -2.52609834e-01,  1.71841382e+00, -1.64863029e+00,  1.04331939e+00,
        1.37119597e+00, -9.36641300e-01, -9.13117608e-01,  9.17069724e-04,
        8.13646327e-01,  7.97381691e-01,  7.26895681e-02,  5.40259084e-01,
       -2.63944631e-02,  9.90007041e-01, -2.83999034e-01,  4.79458795e-01,
        4.89323199e-01])

#### Create the following matrix:

In [51]:
np.matrix(np.random.rand(50))

matrix([[0.11421757, 0.78331023, 0.39823522, 0.86978135, 0.82001597,
         0.29202173, 0.06629527, 0.96640875, 0.95963798, 0.8280131 ,
         0.08297009, 0.09585755, 0.55892527, 0.94589697, 0.34194427,
         0.03493656, 0.05275772, 0.48849206, 0.26157304, 0.09658945,
         0.77894784, 0.58771124, 0.22480872, 0.99969152, 0.20338533,
         0.10568696, 0.82700646, 0.725309  , 0.79780905, 0.42354066,
         0.76331959, 0.0649621 , 0.1900946 , 0.50381022, 0.92810305,
         0.0607052 , 0.84924159, 0.30638738, 0.62312649, 0.93316245,
         0.53520904, 0.60510085, 0.75564913, 0.13242225, 0.26671848,
         0.32372661, 0.75661842, 0.09300639, 0.26292068, 0.92899943]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [46]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [14]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [18]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [20]:
mat[3,-1:]

array([20])

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [29]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [30]:
mat[-1]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [41]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [42]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [43]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [44]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!