In [1]:
import math as m  #importing package

In [2]:
m.sqrt(25)

5.0

# Numpy->Numerical Python
* foundations for mathematical prob,scientic,numerical prob,
* homo multidimensional array
#### Topics
* Creation of 1D,2D,3D Arrays
* Attributes -> ndim,size,dtype,shape,type
* Methods->arange,linspace,ravel,random
* Stacking->hstack,vstack
* Splitting-> hsplit,vsplit
* Broadcasting, Boolean masking 
* Others-> zeros,ones,eye,max,min,copy

In [4]:
import numpy as np

In [5]:
#Create a 1D array
d1 = np.array([3,4,5,8,9])
d1

array([3, 4, 5, 8, 9])

In [6]:
print("The dimension",d1.ndim)
print("The size",d1.size)
print("The datatype",d1.dtype)
print("The type",type(d1))
print("Shape",d1.shape)

The dimension 1
The size 5
The datatype int32
The type <class 'numpy.ndarray'>
Shape (5,)


In [6]:
#CREAte 2D array
d2 = np.array([[1,2,3],[3,4,7]])
d2

array([[1, 2, 3],
       [3, 4, 7]])

In [7]:
print("The shape is",d2.shape)

The shape is (2, 3)


In [8]:
print("The dimension",d2.ndim)
print("The size",d2.size)
print("The datatype",d2.dtype)
print("The type",type(d2))

The dimension 2
The size 6
The datatype int32
The type <class 'numpy.ndarray'>


In [7]:
#Creating a 3D Array
d3 = np.array([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]]])
d3

array([[[1, 2],
        [2, 3],
        [3, 4]],

       [[4, 5],
        [5, 6],
        [6, 7]]])

In [8]:
print("The dimension",d3.ndim)
print("The size",d3.size)
print("The datatype",d3.dtype)
print("The type",type(d3))
print("The shape is",d3.shape) #(3d,2d,1d)

The dimension 3
The size 12
The datatype int32
The type <class 'numpy.ndarray'>
The shape is (2, 3, 2)


# Methods
* arange->similar to range
* linspace
* ravel
* random

In [9]:
np.arange(5) #stop

array([0, 1, 2, 3, 4])

In [10]:
np.arange(1,5) # start,stop

array([1, 2, 3, 4])

In [13]:
np.arange(1,10,1) #start,stop,step

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(50,100,5)

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [15]:
np.arange(50,100,5).reshape(2,5)

array([[50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [16]:
np.arange(50,100,5).reshape(5,2)

array([[50, 55],
       [60, 65],
       [70, 75],
       [80, 85],
       [90, 95]])

In [19]:
np.arange(50,100,5).reshape(5,1,2)

array([[[50, 55]],

       [[60, 65]],

       [[70, 75]],

       [[80, 85]],

       [[90, 95]]])

In [21]:
np.arange(50,100,5).reshape(1,1,2,5)

array([[[[50, 55, 60, 65, 70],
         [75, 80, 85, 90, 95]]]])

In [22]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
np.arange(1,16).reshape(3,5,1,-1)

array([[[[ 1]],

        [[ 2]],

        [[ 3]],

        [[ 4]],

        [[ 5]]],


       [[[ 6]],

        [[ 7]],

        [[ 8]],

        [[ 9]],

        [[10]]],


       [[[11]],

        [[12]],

        [[13]],

        [[14]],

        [[15]]]])

In [24]:
#linspace ->start,stop,no.of elements->(stop-Included)
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [52]:
np.linspace(1,50,10,retstep=True)

(array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
        28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ]),
 5.444444444444445)

In [32]:
#ravel converts array of any dim to a single (1D )
a2 = np.arange(50).reshape(5,5,2)
a2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [33]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [34]:
#random->create random nos->rand->(0,1)
np.random.rand(5)

array([0.44017004, 0.07897503, 0.75517682, 0.75365271, 0.34710982])

In [42]:
np.random.rand(5)*100

array([70.3979379 , 62.39033215, 34.88547805, 30.66089361, 54.63501019])

In [40]:
np.random.randint(5) #within 5 (Exclude) create 1 int random no

2

In [50]:
np.random.randint(1,5)

1

In [47]:
np.random.rand(10).reshape(5,2)

array([[0.09870127, 0.04118815],
       [0.25842785, 0.22403288],
       [0.69349011, 0.23195818],
       [0.01398632, 0.24746256],
       [0.46472497, 0.03171598]])

In [54]:
np.linspace(1,5,4,retstep=True)

(array([1.        , 2.33333333, 3.66666667, 5.        ]), 1.3333333333333333)

In [62]:
a=np.linspace(0,50,11,retstep=True,dtype=str)
a

(array(['0.0', '5.0', '10.0', '15.0', '20.0', '25.0', '30.0', '35.0',
        '40.0', '45.0', '50.0'], dtype='<U32'),
 5.0)

AttributeError: 'tuple' object has no attribute 'dtype'