In [1]:
import math as m  #importing package

In [2]:
m.sqrt(25)

5.0

# Numpy->Numerical Python
* foundations for mathematical prob,scientic,numerical prob,
* homo multidimensional array
#### Topics
* Creation of 1D,2D,3D Arrays
* Attributes -> ndim,size,dtype,shape,type
* Methods->arange,linspace,ravel,random
* Stacking->hstack,vstack
* Splitting-> hsplit,vsplit
* Broadcasting, Boolean masking 
* Others-> zeros,ones,eye,max,min,copy

In [4]:
import numpy as np

In [5]:
#Create a 1D array
d1 = np.array([3,4,5,8,9])
d1

array([3, 4, 5, 8, 9])

In [6]:
print("The dimension",d1.ndim)
print("The size",d1.size)
print("The datatype",d1.dtype)
print("The type",type(d1))
print("Shape",d1.shape)

The dimension 1
The size 5
The datatype int32
The type <class 'numpy.ndarray'>
Shape (5,)


In [6]:
#CREAte 2D array
d2 = np.array([[1,2,3],[3,4,7]])
d2

array([[1, 2, 3],
       [3, 4, 7]])

In [7]:
print("The shape is",d2.shape)

The shape is (2, 3)


In [8]:
print("The dimension",d2.ndim)
print("The size",d2.size)
print("The datatype",d2.dtype)
print("The type",type(d2))

The dimension 2
The size 6
The datatype int32
The type <class 'numpy.ndarray'>


In [7]:
#Creating a 3D Array
d3 = np.array([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]]])
d3

array([[[1, 2],
        [2, 3],
        [3, 4]],

       [[4, 5],
        [5, 6],
        [6, 7]]])

In [8]:
print("The dimension",d3.ndim)
print("The size",d3.size)
print("The datatype",d3.dtype)
print("The type",type(d3))
print("The shape is",d3.shape) #(3d,2d,1d)

The dimension 3
The size 12
The datatype int32
The type <class 'numpy.ndarray'>
The shape is (2, 3, 2)


# Methods
* arange->similar to range
* linspace
* ravel
* random

In [9]:
np.arange(5) #stop

array([0, 1, 2, 3, 4])

In [10]:
np.arange(1,5) # start,stop

array([1, 2, 3, 4])

In [13]:
np.arange(1,10,1) #start,stop,step

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(50,100,5)

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [15]:
np.arange(50,100,5).reshape(2,5)

array([[50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [16]:
np.arange(50,100,5).reshape(5,2)

array([[50, 55],
       [60, 65],
       [70, 75],
       [80, 85],
       [90, 95]])

In [19]:
np.arange(50,100,5).reshape(5,1,2)

array([[[50, 55]],

       [[60, 65]],

       [[70, 75]],

       [[80, 85]],

       [[90, 95]]])

In [21]:
np.arange(50,100,5).reshape(1,1,2,5)

array([[[[50, 55, 60, 65, 70],
         [75, 80, 85, 90, 95]]]])

In [22]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
np.arange(1,16).reshape(3,5,1,-1)

array([[[[ 1]],

        [[ 2]],

        [[ 3]],

        [[ 4]],

        [[ 5]]],


       [[[ 6]],

        [[ 7]],

        [[ 8]],

        [[ 9]],

        [[10]]],


       [[[11]],

        [[12]],

        [[13]],

        [[14]],

        [[15]]]])

In [24]:
#linspace ->start,stop,no.of elements->(stop-Included)
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [52]:
np.linspace(1,50,10,retstep=True)

(array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
        28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ]),
 5.444444444444445)

In [32]:
#ravel converts array of any dim to a single (1D )
a2 = np.arange(50).reshape(5,5,2)
a2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [33]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [34]:
#random->create random nos->rand->(0,1)
np.random.rand(5)

array([0.44017004, 0.07897503, 0.75517682, 0.75365271, 0.34710982])

In [42]:
np.random.rand(5)*100

array([70.3979379 , 62.39033215, 34.88547805, 30.66089361, 54.63501019])

In [40]:
np.random.randint(5) #within 5 (Exclude) create 1 int random no

2

In [50]:
np.random.randint(1,5)

1

In [47]:
np.random.rand(10).reshape(5,2)

array([[0.09870127, 0.04118815],
       [0.25842785, 0.22403288],
       [0.69349011, 0.23195818],
       [0.01398632, 0.24746256],
       [0.46472497, 0.03171598]])

In [54]:
np.linspace(1,5,4,retstep=True)

(array([1.        , 2.33333333, 3.66666667, 5.        ]), 1.3333333333333333)

In [62]:
a=np.linspace(0,50,11,retstep=True,dtype=str)
a

(array(['0.0', '5.0', '10.0', '15.0', '20.0', '25.0', '30.0', '35.0',
        '40.0', '45.0', '50.0'], dtype='<U32'),
 5.0)

In [66]:
a=np.linspace(1,50,5)

In [67]:
a

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [68]:
type(a)

numpy.ndarray

In [72]:
a=np.linspace(0,50,11)
type(a)
a

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [74]:
np.random.randint(1,50,5)

array([28, 26,  8,  6, 38])

# Stacking
* hstack
* vstack

In [22]:
a1= np.arange(10,50).reshape(10,4)
a1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45],
       [46, 47, 48, 49]])

In [24]:
a2=np.linspace(10,50,40).reshape(10,4)
a2

array([[10.        , 11.02564103, 12.05128205, 13.07692308],
       [14.1025641 , 15.12820513, 16.15384615, 17.17948718],
       [18.20512821, 19.23076923, 20.25641026, 21.28205128],
       [22.30769231, 23.33333333, 24.35897436, 25.38461538],
       [26.41025641, 27.43589744, 28.46153846, 29.48717949],
       [30.51282051, 31.53846154, 32.56410256, 33.58974359],
       [34.61538462, 35.64102564, 36.66666667, 37.69230769],
       [38.71794872, 39.74358974, 40.76923077, 41.79487179],
       [42.82051282, 43.84615385, 44.87179487, 45.8974359 ],
       [46.92307692, 47.94871795, 48.97435897, 50.        ]])

In [27]:
type(a2)

numpy.ndarray

In [29]:
a2.dtype

dtype('float64')

In [30]:
a1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45],
       [46, 47, 48, 49]])

In [31]:
a2

array([[10.        , 11.02564103, 12.05128205, 13.07692308],
       [14.1025641 , 15.12820513, 16.15384615, 17.17948718],
       [18.20512821, 19.23076923, 20.25641026, 21.28205128],
       [22.30769231, 23.33333333, 24.35897436, 25.38461538],
       [26.41025641, 27.43589744, 28.46153846, 29.48717949],
       [30.51282051, 31.53846154, 32.56410256, 33.58974359],
       [34.61538462, 35.64102564, 36.66666667, 37.69230769],
       [38.71794872, 39.74358974, 40.76923077, 41.79487179],
       [42.82051282, 43.84615385, 44.87179487, 45.8974359 ],
       [46.92307692, 47.94871795, 48.97435897, 50.        ]])

In [32]:
np.hstack((a1,a2))

array([[10.        , 11.        , 12.        , 13.        , 10.        ,
        11.02564103, 12.05128205, 13.07692308],
       [14.        , 15.        , 16.        , 17.        , 14.1025641 ,
        15.12820513, 16.15384615, 17.17948718],
       [18.        , 19.        , 20.        , 21.        , 18.20512821,
        19.23076923, 20.25641026, 21.28205128],
       [22.        , 23.        , 24.        , 25.        , 22.30769231,
        23.33333333, 24.35897436, 25.38461538],
       [26.        , 27.        , 28.        , 29.        , 26.41025641,
        27.43589744, 28.46153846, 29.48717949],
       [30.        , 31.        , 32.        , 33.        , 30.51282051,
        31.53846154, 32.56410256, 33.58974359],
       [34.        , 35.        , 36.        , 37.        , 34.61538462,
        35.64102564, 36.66666667, 37.69230769],
       [38.        , 39.        , 40.        , 41.        , 38.71794872,
        39.74358974, 40.76923077, 41.79487179],
       [42.        , 43.        

In [33]:
np.vstack((a1,a2))

array([[10.        , 11.        , 12.        , 13.        ],
       [14.        , 15.        , 16.        , 17.        ],
       [18.        , 19.        , 20.        , 21.        ],
       [22.        , 23.        , 24.        , 25.        ],
       [26.        , 27.        , 28.        , 29.        ],
       [30.        , 31.        , 32.        , 33.        ],
       [34.        , 35.        , 36.        , 37.        ],
       [38.        , 39.        , 40.        , 41.        ],
       [42.        , 43.        , 44.        , 45.        ],
       [46.        , 47.        , 48.        , 49.        ],
       [10.        , 11.02564103, 12.05128205, 13.07692308],
       [14.1025641 , 15.12820513, 16.15384615, 17.17948718],
       [18.20512821, 19.23076923, 20.25641026, 21.28205128],
       [22.30769231, 23.33333333, 24.35897436, 25.38461538],
       [26.41025641, 27.43589744, 28.46153846, 29.48717949],
       [30.51282051, 31.53846154, 32.56410256, 33.58974359],
       [34.61538462, 35.

In [34]:
#Create 2 arrays, 1st array->15(0-14) 2nd array->15(20-34)
# Use hstack and vstack
ab1=np.arange(15).reshape(5,3)
ab2=np.arange(20,35).reshape(5,3)
print(ab1)
print(ab2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]]


In [35]:
np.hstack((ab1,ab2))

array([[ 0,  1,  2, 20, 21, 22],
       [ 3,  4,  5, 23, 24, 25],
       [ 6,  7,  8, 26, 27, 28],
       [ 9, 10, 11, 29, 30, 31],
       [12, 13, 14, 32, 33, 34]])

In [36]:
np.vstack((ab1,ab2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34]])

In [37]:
np.hstack((ab1,ab2,ab1))

array([[ 0,  1,  2, 20, 21, 22,  0,  1,  2],
       [ 3,  4,  5, 23, 24, 25,  3,  4,  5],
       [ 6,  7,  8, 26, 27, 28,  6,  7,  8],
       [ 9, 10, 11, 29, 30, 31,  9, 10, 11],
       [12, 13, 14, 32, 33, 34, 12, 13, 14]])

In [39]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
#Split->hsplit,vsplit
ab1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [41]:
ab2

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34]])

In [44]:
np.hsplit(ab1,3)

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14]])]

In [45]:
np.vsplit(ab1,5)

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]]),
 array([[12, 13, 14]])]

In [46]:
a3=np.arange(24).reshape(6,4)
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
np.hsplit(a3,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [48]:
np.hsplit(a3,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16],
        [20]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17],
        [21]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]])]

In [49]:
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
np.vsplit(a3,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [51]:
np.vsplit(a3,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [52]:
np.vsplit(a3,6)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [54]:
a10 = np.arange(24).reshape(2,3,4)
a11= np.hsplit(a10,3)
print(a10)
print(a11)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[array([[[ 0,  1,  2,  3]],

       [[12, 13, 14, 15]]]), array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]]), array([[[ 8,  9, 10, 11]],

       [[20, 21, 22, 23]]])]


In [55]:
# Broadcasting 
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [56]:
a3[0:2,]=50

In [57]:
a3

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
a3[4:,1:3]=50
a3

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 50, 50, 19],
       [20, 50, 50, 23]])

In [93]:
ab1

array([[  0, 100,   2],
       [  3, 100,   5],
       [  6, 100,   8],
       [  9, 100,  11],
       [ 12, 100,  50]])

In [94]:
# 2nd & 3rd column replace with 100
ab1[:,1:3] = 100
ab1

array([[  0, 100, 100],
       [  3, 100, 100],
       [  6, 100, 100],
       [  9, 100, 100],
       [ 12, 100, 100]])

In [64]:
ab1[4:,2:] = 50
ab1

array([[  0, 100,   2],
       [  3, 100,   5],
       [  6, 100,   8],
       [  9, 100,  11],
       [ 12, 100,  50]])

In [65]:
# Boolean Masking
ab1

array([[  0, 100,   2],
       [  3, 100,   5],
       [  6, 100,   8],
       [  9, 100,  11],
       [ 12, 100,  50]])

In [66]:
re = 0 == ab1%2 # re= ab1%2==0

In [68]:
ab1[re]

array([  0, 100,   2, 100,   6, 100,   8, 100,  12, 100,  50])

In [69]:
re

array([[ True,  True,  True],
       [False,  True, False],
       [ True,  True,  True],
       [False,  True, False],
       [ True,  True,  True]])

In [70]:
re1 = 0 == ab1%3
re1

array([[ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False]])

In [71]:
#zeros,ones,eye,max,min,copy
np.zeros(2)

array([0., 0.])

In [72]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [75]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [76]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
ab1

array([[  0, 100,   2],
       [  3, 100,   5],
       [  6, 100,   8],
       [  9, 100,  11],
       [ 12, 100,  50]])

In [79]:
np.max(ab1)

100

In [80]:
np.min(ab1)

0

In [82]:
ab3=ab1.copy()
ab3

array([[  0, 100,   2],
       [  3, 100,   5],
       [  6, 100,   8],
       [  9, 100,  11],
       [ 12, 100,  50]])

In [83]:
np.eye(5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [86]:
ab4=ab1

In [87]:
ab4

array([[  0, 100,   2],
       [  3, 100,   5],
       [  6, 100,   8],
       [  9, 100,  11],
       [ 12, 100,  50]])

In [88]:
ab1

array([[  0, 100,   2],
       [  3, 100,   5],
       [  6, 100,   8],
       [  9, 100,  11],
       [ 12, 100,  50]])

In [89]:
ab4

array([[  0, 100,   2],
       [  3, 100,   5],
       [  6, 100,   8],
       [  9, 100,  11],
       [ 12, 100,  50]])

In [90]:
b=ab1+ab4
b

array([[  0, 200,   4],
       [  6, 200,  10],
       [ 12, 200,  16],
       [ 18, 200,  22],
       [ 24, 200, 100]])

In [92]:
c=ab1-ab4
c

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])