How Array is Good in performs

Write a program to see perform of list and array 



In [1]:
import numpy as np

In [6]:
my_list1=[2,4,1,7,8,9,14,12]


In [8]:
np1=np.array(my_list1)
np1

array([ 2,  4,  1,  7,  8,  9, 14, 12])

In [9]:
np1.shape

(8,)

In [10]:
np1.ndim

1

In [9]:
my_list2=[[1,3,4],[4,5,6],[6,7,8]]

In [10]:
np1=np.array(my_list2)
np1

array([[1, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [20]:
np2=np.arange(3,15,3)
np2

array([ 3,  6,  9, 12])

In [ ]:
np2=np.arange(3,15)
np2

In [23]:
np2=np.arange(3,15).reshape(4,3)
np2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [24]:
np2.shape

(4, 3)

In [28]:
np3=np.random.random(12).round()
np3

array([0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1.])

In [29]:
np3[:8]

array([0., 0., 0., 1., 0., 1., 0., 0.])

In [39]:
np.random.rand(2,3)


array([[0.57526398, 0.73051488, 0.15672901],
       [0.90143878, 0.68238978, 0.76748234]])

In [50]:
np.random.randint(2,8)

7

In [49]:
np.random.random_integers(3,9)

<ipython-input-49-0ebc29a11495>:1: DeprecationWarning: This function is deprecated. Please call randint(3, 9 + 1) instead
  np.random.random_integers(3,9)


9

In [55]:
np.random.randn(2,10)

array([[-0.58621947,  1.63412727,  1.07571311, -0.10173396,  0.80142431,
        -0.36186115, -0.73210316,  2.22343834,  0.10220356,  0.48149735],
       [ 0.22885882, -0.92391852,  0.71361006, -0.12530561, -2.27723994,
         0.23001364,  0.8644387 , -1.31611686,  0.68689814, -0.99997774]])

In [36]:
%%timeit
list1=[]
for i in range(1,10000):
    list1.append(i)

522 µs ± 4.85 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [37]:
%%timeit
np10=np.arange(1,10000)

4.47 µs ± 25.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [57]:
np.eye(4) #diagonal matraics

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np3=np.random.random(12).round().reshape(3,4)
np3

array([[0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [77]:
np3[0:2,2:]

array([[1., 0.],
       [0., 1.]])

In [78]:
np3[1:,2:]

array([[0., 1.],
       [1., 1.]])

In [86]:
np.linspace(2,4,5)

array([2. , 2.5, 3. , 3.5, 4. ])